/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VntLibreria;

/**
 *
 * @author HP
 */
public class Recomienda extends javax.swing.JFrame
{

    /**
     * Creates new form Recomienda
     */
    public Recomienda()
    {
        initComponents();
        componenetesRecomendacion(jPanel1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, 490, 441));

        pack();
    }// </editor-fold>//GEN-END:initComponents

//  jPanel1.add(panelRecomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 360));
//
//        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 441));
    public void componenetesRecomendacion(javax.swing.JPanel v)
    {
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel panelRecomienda = new javax.swing.JPanel();
        javax.swing.JLabel etirquetaTituloLibro1 = new javax.swing.JLabel();
        javax.swing.JLabel etiquetaAutorLibro1 = new javax.swing.JLabel();
        javax.swing.JLabel etiquetaEditorial1 = new javax.swing.JLabel();
        javax.swing.JLabel etiqueta4 = new javax.swing.JLabel();
        javax.swing.JLabel etiqueta5 = new javax.swing.JLabel();
        javax.swing.JLabel etiqueta6 = new javax.swing.JLabel();
        javax.swing.JPanel panelImagenRecomienda = new javax.swing.JPanel();
        rojeru_san.RSButton bntDescripcion1 = new rojeru_san.RSButton();
        javax.swing.JCheckBox jCheckBox1 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox2 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox3 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox4 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox5 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRecomienda.setBackground(new java.awt.Color(255, 255, 255));
        panelRecomienda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));

        panelRecomienda.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                if (jCheckBox1.isSelected())
                {
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                } else if (jCheckBox2.isSelected())
                {
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                } else if (jCheckBox3.isSelected())
                {
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                } else if (jCheckBox4.isSelected())
                {
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                } else if (jCheckBox5.isSelected())
                {

                } else
                {
                    jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                }

            }
        });
        panelRecomienda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etirquetaTituloLibro1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etirquetaTituloLibro1.setText("Nombre del libro");
        panelRecomienda.add(etirquetaTituloLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 150, -1));

        etiquetaAutorLibro1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiquetaAutorLibro1.setText("Autor");
        panelRecomienda.add(etiquetaAutorLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 160, 20));

        etiquetaEditorial1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiquetaEditorial1.setText("Editorial");
        panelRecomienda.add(etiquetaEditorial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 170, -1));

        etiqueta4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiqueta4.setForeground(new java.awt.Color(102, 102, 102));
        etiqueta4.setText("Nombre del libro:");
        panelRecomienda.add(etiqueta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        etiqueta5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiqueta5.setForeground(new java.awt.Color(102, 102, 102));
        etiqueta5.setText("Autor:");
        panelRecomienda.add(etiqueta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 40, -1));

        etiqueta6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiqueta6.setForeground(new java.awt.Color(102, 102, 102));
        etiqueta6.setText("Editorial:");
        panelRecomienda.add(etiqueta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, -1));

        javax.swing.GroupLayout panelImagenRecomiendaLayout = new javax.swing.GroupLayout(panelImagenRecomienda);
        panelImagenRecomienda.setLayout(panelImagenRecomiendaLayout);
        panelImagenRecomiendaLayout.setHorizontalGroup(
                panelImagenRecomiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 130, Short.MAX_VALUE)
        );
        panelImagenRecomiendaLayout.setVerticalGroup(
                panelImagenRecomiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 150, Short.MAX_VALUE)
        );

        panelRecomienda.add(panelImagenRecomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));

        bntDescripcion1.setBackground(new java.awt.Color(0, 51, 102));
        bntDescripcion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Up_24px.png"))); // NOI18N
        bntDescripcion1.setText("Ver descripción");
        bntDescripcion1.setColorHover(new java.awt.Color(0, 102, 204));

        bntDescripcion1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                /*
                Que se desea hacer una vez que se oprima el boton
                 */
            }
        });
        panelRecomienda.add(bntDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 310, 310, -1));

        jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png"))); // NOI18N
        jCheckBox1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star.png"))); // NOI18N
        jCheckBox1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png"))); // NOI18N
        jCheckBox1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (2).png"))); // NOI18N

        jCheckBox1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                if (!(jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected()))
                {
                    jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                }
            }
        });

        jCheckBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(false);
                jCheckBox3.setSelected(false);
                jCheckBox4.setSelected(false);
                jCheckBox5.setSelected(false);
                jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
            }
        });
        panelRecomienda.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 30));

        jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png"))); // NOI18N
        jCheckBox2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star.png"))); // NOI18N
        jCheckBox2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png"))); // NOI18N
        jCheckBox2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (2).png"))); // NOI18N

        jCheckBox2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                if (!(jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected()))
                {
                    jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));

                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                }
            }
        });

        jCheckBox2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {

                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(true);
                jCheckBox3.setSelected(false);
                jCheckBox4.setSelected(false);
                jCheckBox5.setSelected(false);
                jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));

            }
        });
        panelRecomienda.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 30));

        jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png"))); // NOI18N
        jCheckBox3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star.png"))); // NOI18N
        jCheckBox3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png"))); // NOI18N
        jCheckBox3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (2).png"))); // NOI18N

        jCheckBox3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                if (!(jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected()))
                {
                    jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));

                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                }
            }
        });

        jCheckBox3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(true);
                jCheckBox3.setSelected(true);
                jCheckBox4.setSelected(false);
                jCheckBox5.setSelected(false);
                jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
            }
        });
        panelRecomienda.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 30));

        jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png"))); // NOI18N
        jCheckBox4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star.png"))); // NOI18N
        jCheckBox4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png"))); // NOI18N
        jCheckBox4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (2).png"))); // NOI18N

        jCheckBox4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                if (!(jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected()))
                {
                    jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));

                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                }
            }
        });

        jCheckBox4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(true);
                jCheckBox3.setSelected(true);
                jCheckBox4.setSelected(true);
                jCheckBox5.setSelected(false);
                jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
            }
        });
        panelRecomienda.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, 30));

        jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png"))); // NOI18N
        jCheckBox5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star.png"))); // NOI18N
        jCheckBox5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png"))); // NOI18N
        jCheckBox5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (2).png"))); // NOI18N

        jCheckBox5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                if (!(jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected()))
                {
                    jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));

                }
            }
        });

        jCheckBox5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(true);
                jCheckBox3.setSelected(true);
                jCheckBox4.setSelected(true);
                jCheckBox5.setSelected(true);
            }
        });
        panelRecomienda.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 30));
        v.add(panelRecomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 360));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Recomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Recomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Recomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Recomienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new Recomienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
