/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VntLibreria;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.awt.MouseInfo;
import java.awt.Point;
import java.net.URI;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import recursos.Mensaje;
import recursos.Validaciones;

/**
 *
 * @author HP
 */
public class VtnActulizarPassword extends javax.swing.JFrame
{

    /**
     * Creates new form VtnActulizarPassword
     */
    //VARIABLE ENTERA PARA CONOCER LA POSISION EN X DE LA VENTANA
    int X_V;
    //VARIABLE ENTERA PARA CONOCER LA POSISION EN Y DE LA VENTANA
    int Y_V;
    String pantallas_Usuario = "";
    String nombre_Final_de_Usuario = "";

    public VtnActulizarPassword(String pantallas_Usuario, String nombre_Final_de_Usuario)
    {
        this.pantallas_Usuario = pantallas_Usuario;
        this.nombre_Final_de_Usuario = nombre_Final_de_Usuario;
        initComponents();
         Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenesG/buhoAzul.png"));
        setIconImage(icono);
        //   setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        this.setLocationRelativeTo(null);


    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rSButton1 = new rojeru_san.RSButton();
        rSButton2 = new rojeru_san.RSButton();
        rSButton3 = new rojeru_san.RSButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        u = new rojeru_san.RSMTextFull();
        pa = new rojeru_san.RSMPassView();
        cpn = new rojeru_san.RSMPassView();
        pn = new rojeru_san.RSMPassView();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(870, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel3.setText("Ingresa el usuario:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 150, -1, -1));

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setText("Confirmar contraseña nueva:");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setText("Actualización de contraseña");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 40, 600, -1));

        jLabel6.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel6.setText("Contraseña antigua:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, -1, -1));

        jLabel7.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel7.setText("Contraseña nueva:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 270, -1, -1));

        rSButton1.setBackground(new java.awt.Color(0, 51, 102));
        rSButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Vote_24px_1.png"))); // NOI18N
        rSButton1.setText("Aceptar");
        rSButton1.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 470, -1, -1));

        rSButton2.setBackground(new java.awt.Color(0, 51, 102));
        rSButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118917 - clear edit.png"))); // NOI18N
        rSButton2.setText("Limpiar");
        rSButton2.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 470, 180, 40));

        rSButton3.setBackground(new java.awt.Color(0, 51, 102));
        rSButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Exit.png"))); // NOI18N
        rSButton3.setText("Regresar");
        rSButton3.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 470, -1, -1));

        jPanel3.setBackground(new java.awt.Color(0, 0, 51));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/IMAGEN2.JPG"))); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 380));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 530, 590));

        u.setForeground(new java.awt.Color(0, 51, 102));
        u.setBordeColorFocus(new java.awt.Color(0, 51, 102));
        u.setBotonColor(new java.awt.Color(0, 51, 102));
        u.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        u.setOpaque(false);
        jPanel1.add(u, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 130, 190, -1));

        pa.setForeground(new java.awt.Color(0, 51, 102));
        pa.setBordeColorFocus(new java.awt.Color(0, 51, 102));
        pa.setBotonColor(new java.awt.Color(0, 51, 102));
        pa.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pa.setOpaque(false);
        jPanel1.add(pa, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 190, 290, -1));

        cpn.setForeground(new java.awt.Color(0, 51, 102));
        cpn.setBordeColorFocus(new java.awt.Color(0, 51, 102));
        cpn.setBotonColor(new java.awt.Color(0, 51, 102));
        cpn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cpn.setOpaque(false);
        jPanel1.add(cpn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 290, -1));

        pn.setForeground(new java.awt.Color(0, 51, 102));
        pn.setBordeColorFocus(new java.awt.Color(0, 51, 102));
        pn.setBotonColor(new java.awt.Color(0, 51, 102));
        pn.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        pn.setOpaque(false);
        jPanel1.add(pn, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 250, 290, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton1ActionPerformed
    {//GEN-HEADEREND:event_rSButton1ActionPerformed

        try
        {
            Conexion.con = Conexion.getConexion();
            PreparedStatement ps = Conexion.con.prepareStatement("SELECT * FROM t_usuario where usuar=? AND password=?");
            String contrase = new String(pa.getPassword());
            String nuevopasword = Hash.sha1(contrase);
            ps.setString(1, u.getText());
            ps.setString(2, nuevopasword);
            ResultSet rs;
            rs = ps.executeQuery();
            if (rs.next())
            {
                if (pn.getText().equals(cpn.getText()))
                {
                    int id = rs.getInt("id_usuar");
                    Conexion.con = Conexion.getConexion();
                    String sql = "UPDATE t_usuario SET password=? WHERE id_usuar=?";
                    PreparedStatement registro = Conexion.con.prepareStatement(sql);
                    String contrases = new String(pn.getPassword());
                    String nuevopaswords = Hash.sha1(contrases);
                    registro.setString(1, nuevopaswords);
                    registro.setInt(2, id);
                    int rh = registro.executeUpdate();

                    if (rh > 0)
                    {
                        Conexion.con = Conexion.getConexion();
                        String sqlactualizacion = "UPDATE t_actualizaciones_de_contraseñas SET ultima_actualizacion=? WHERE usuar=?";
                        PreparedStatement actualiza = Conexion.con.prepareStatement(sqlactualizacion);
                        Date date = new Date();
                        DateFormat fecha = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss"); //para la fecha y hora // yyyy-MM-dd HH:mm:ss//modificar
                        actualiza.setString(1, fecha.format(date));
                        actualiza.setString(2, u.getText());
                        actualiza.execute();

                    }
                }

            } else
            {
                Mensaje.error(this, "Usuario o contraseña incorrectas");
            }

            CtrComponentes.limpiaTodo(pn, pa, cpn, u);
        } catch (SQLException ex)
        {
            Mensaje.errorException(this, "Ha ocurrido un error \n" + ex.toString());
        }
    }//GEN-LAST:event_rSButton1ActionPerformed

    private void rSButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton3ActionPerformed
    {//GEN-HEADEREND:event_rSButton3ActionPerformed
        CtrComponentes.botonSalirSI(this, nombre_Final_de_Usuario, pantallas_Usuario);
    }//GEN-LAST:event_rSButton3ActionPerformed

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton2ActionPerformed
    {//GEN-HEADEREND:event_rSButton2ActionPerformed
        CtrComponentes.limpiaTodo(pn, pa, cpn, u);
    }//GEN-LAST:event_rSButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rojeru_san.RSMPassView cpn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private rojeru_san.RSMPassView pa;
    private rojeru_san.RSMPassView pn;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButton rSButton3;
    private rojeru_san.RSMTextFull u;
    // End of variables declaration//GEN-END:variables
}
