/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VntLibreria;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.HeadlessException;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.awt.MouseInfo;
import java.awt.Point;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import recursos.Mensaje;

/**
 *
 * @author HP
 */
public class VtnBajasLibros extends javax.swing.JFrame
{

    /**
     * Creates new form VtnBajasLibros
     */
    int X_V;
    int Y_V;
    String pantallas_Usuario = "";
    String nombre_Final_de_Usuario = "";

    public VtnBajasLibros(String pantallas_Usuario, String nombre_Final_de_Usuario)
    {
        this.pantallas_Usuario = pantallas_Usuario;
        this.nombre_Final_de_Usuario = nombre_Final_de_Usuario;
        initComponents();
         Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenesG/buhoAzul.png"));
        setIconImage(icono);
        //   setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rSButton2 = new rojeru_san.RSButton();
        rSButton3 = new rojeru_san.RSButton();
        jTextField1 = new rojeru_san.RSMTextFull();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1260, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Eliminar libro");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseReleased(java.awt.event.MouseEvent evt)
            {
                jLabel1MouseReleased(evt);
            }
        });
        jLabel1.addPropertyChangeListener(new java.beans.PropertyChangeListener()
        {
            public void propertyChange(java.beans.PropertyChangeEvent evt)
            {
                jLabel1PropertyChange(evt);
            }
        });
        jLabel1.addVetoableChangeListener(new java.beans.VetoableChangeListener()
        {
            public void vetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException
            {
                jLabel1VetoableChange(evt);
            }
        });
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 100, 267, 40));

        jLabel3.setText("Nombre del libro:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 130, 20));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/FB_IMG_1525560169324.jpg"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 440, 420));

        rSButton2.setBackground(new java.awt.Color(0, 51, 102));
        rSButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Delete_24px.png"))); // NOI18N
        rSButton2.setText("Eliminar");
        rSButton2.setColorHover(new java.awt.Color(0, 102, 255));
        rSButton2.addChangeListener(new javax.swing.event.ChangeListener()
        {
            public void stateChanged(javax.swing.event.ChangeEvent evt)
            {
                rSButton2StateChanged(evt);
            }
        });
        rSButton2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseDragged(java.awt.event.MouseEvent evt)
            {
                rSButton2MouseDragged(evt);
            }
        });
        rSButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, -1, -1));

        rSButton3.setBackground(new java.awt.Color(0, 51, 102));
        rSButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px.png"))); // NOI18N
        rSButton3.setText("Regresar");
        rSButton3.setColorHover(new java.awt.Color(0, 102, 255));
        rSButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(990, 380, -1, -1));

        jTextField1.setForeground(new java.awt.Color(0, 51, 102));
        jTextField1.setBordeColorFocus(new java.awt.Color(0, 51, 102));
        jTextField1.setBotonColor(new java.awt.Color(0, 51, 102));
        jTextField1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jTextField1.setOpaque(false);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 220, 190, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void boton8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boton8ActionPerformed
    {//GEN-HEADEREND:event_boton8ActionPerformed

    }//GEN-LAST:event_boton8ActionPerformed

    private void boton9ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boton9ActionPerformed
    {//GEN-HEADEREND:event_boton9ActionPerformed

    }//GEN-LAST:event_boton9ActionPerformed

    private void rSButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton3ActionPerformed
    {//GEN-HEADEREND:event_rSButton3ActionPerformed
        CtrComponentes.botonSalirSI(this, nombre_Final_de_Usuario, pantallas_Usuario);
    }//GEN-LAST:event_rSButton3ActionPerformed

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton2ActionPerformed
    {//GEN-HEADEREND:event_rSButton2ActionPerformed
        eliminar();
        CtrComponentes.limpiaTodo(jTextField1);
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void jLabel1MouseReleased(java.awt.event.MouseEvent evt)//GEN-FIRST:event_jLabel1MouseReleased
    {//GEN-HEADEREND:event_jLabel1MouseReleased

    }//GEN-LAST:event_jLabel1MouseReleased

    private void jLabel1PropertyChange(java.beans.PropertyChangeEvent evt)//GEN-FIRST:event_jLabel1PropertyChange
    {//GEN-HEADEREND:event_jLabel1PropertyChange

    }//GEN-LAST:event_jLabel1PropertyChange

    private void jLabel1VetoableChange(java.beans.PropertyChangeEvent evt)throws java.beans.PropertyVetoException//GEN-FIRST:event_jLabel1VetoableChange
    {//GEN-HEADEREND:event_jLabel1VetoableChange

    }//GEN-LAST:event_jLabel1VetoableChange

    private void rSButton2StateChanged(javax.swing.event.ChangeEvent evt)//GEN-FIRST:event_rSButton2StateChanged
    {//GEN-HEADEREND:event_rSButton2StateChanged

    }//GEN-LAST:event_rSButton2StateChanged

    private void rSButton2MouseDragged(java.awt.event.MouseEvent evt)//GEN-FIRST:event_rSButton2MouseDragged
    {//GEN-HEADEREND:event_rSButton2MouseDragged

    }//GEN-LAST:event_rSButton2MouseDragged
    public void eliminar()
    {
        Conexion.con = Conexion.getConexion();
        String sql = "DELETE FROM t_libro WHERE nombre_libro=?";
        try
        {
            PreparedStatement registro = Conexion.con.prepareStatement(sql);

            registro.setString(1, jTextField1.getText());
            //Actualiz los registros
            int rh = registro.executeUpdate();

            if (rh > 0)
            {
                JOptionPane.showMessageDialog(null, "Registro eliminado");

            } else
            {
                JOptionPane.showMessageDialog(null, "Registro no eliminado");
            }
        } catch (HeadlessException | SQLException e)
        {
            Mensaje.errorException(this, "Ha ocurrido un error \n" + e.toString());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private rojeru_san.RSMTextFull jTextField1;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButton rSButton3;
    // End of variables declaration//GEN-END:variables
}
