/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VntLibreria;

import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JColorChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import recursos.Mensaje;

/**
 *
 * @author HP
 */
public class VtnBibliotecaVISITANTE extends javax.swing.JFrame
{

    /**
     * Creates new form VtnBiblioteca
     */
    int x, y;
    String pantallas_Usuario = "";
    String nombre_Final_de_Usuario = "";

    public JLabel getjLabel3()
    {
        return jLabel3;
    }

    public void setjLabel3(JLabel jLabel3)
    {
        this.jLabel3 = jLabel3;
    }

    public JLabel getjLabel4()
    {
        return jLabel4;
    }

    public void setjLabel4(JLabel jLabel4)
    {
        this.jLabel4 = jLabel4;
    }

    public JLabel getjLabel5()
    {
        return jLabel5;
    }

    public void setjLabel5(JLabel jLabel5)
    {
        this.jLabel5 = jLabel5;
    }

    public JLabel getjLabel6()
    {
        return jLabel6;
    }

    public void setjLabel6(JLabel jLabel6)
    {
        this.jLabel6 = jLabel6;
    }

    public JLabel getjLabel7()
    {
        return jLabel7;
    }

    public void setjLabel7(JLabel jLabel7)
    {
        this.jLabel7 = jLabel7;
    }

    public JLabel getjLabel8()
    {
        return jLabel8;
    }

    public void setjLabel8(JLabel jLabel8)
    {
        this.jLabel8 = jLabel8;
    }

    public VtnBibliotecaVISITANTE(String pantallas_Usuario, String nombre_Final_de_Usuario)
    {
        this.pantallas_Usuario = pantallas_Usuario;
        this.nombre_Final_de_Usuario = nombre_Final_de_Usuario;
        try
        {
            initComponents();
            NotificacionBienvenido n = new NotificacionBienvenido();
            n.setVisible(true);
            //jPanel1.setBackground(VtnPrincipal.colorPE);
             Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenesG/buhoAzul.png"));
            setIconImage(icono);
            
          
            //jTextField1.setVisible(false);
            //  this.setExtendedState(MAXIMIZED_BOTH);
            //   setDefaultCloseOperation(DISPOSE_ON_CLOSE);
            setResizable(false);
            this.setLocationRelativeTo(null);

            Conexion.con = Conexion.getConexion();
            PreparedStatement ps = Conexion.con.prepareStatement("SELECT * FROM t_persona where usuar=?");
            ps.setString(1, nombre_Final_de_Usuario);
            ResultSet rs;
            rs = ps.executeQuery();
            if (rs.next())
            {
                try
                {
                    Date date = new Date();
                    DateFormat fecha = new SimpleDateFormat("yyyy-MM-dd"); //para la fecha y hora // yyyy-MM-dd HH:mm:ss//modificar

                    String fechaSystem = fecha.format(date);
                    String fechaUsuario = rs.getString("fecha_nacimiento_usu");
                    char fSystem[] = fechaSystem.toCharArray();
                    char fUsuar[] = fechaUsuario.toCharArray();
//2019-06-24
//0123456789
                    if (fSystem[5] == fUsuar[5] && fSystem[6] == fUsuar[6] && fSystem[8] == fUsuar[8] && fSystem[9] == fUsuar[9])
                    {

                        // Retardos.nombre = rs.getString("nombre_usu");
                        //      Retardos.Notificacion3.start();
                        //txtFelicitaciones.setText("Feliz cumpleaños \n" + rs.getString("nombre") + "!");
                    }
                } catch (SQLException ex)
                {

                }

            }
        } catch (SQLException ex)
        {

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        move1 = new com.sun.animation.effects.Move();
        jPanel1 = new javax.swing.JPanel();
        jButton10 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        panelMenu = new javax.swing.JPanel();
        rSButton1 = new rojeru_san.RSButton();
        rSButton2 = new rojeru_san.RSButton();
        rSButton3 = new rojeru_san.RSButton();
        rSButton4 = new rojeru_san.RSButton();
        rSButton5 = new rojeru_san.RSButton();
        rSButton6 = new rojeru_san.RSButton();
        rSButton7 = new rojeru_san.RSButton();
        jPanel3 = new javax.swing.JPanel();
        panelF = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter()
        {
            public void windowOpened(java.awt.event.WindowEvent evt)
            {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/menu.png"))); // NOI18N
        jButton10.setBorder(null);
        jButton10.setContentAreaFilled(false);
        jButton10.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 70, 40));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48/285653 - enveloppe.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 60, 50));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48/285653 - enveloppe.png"))); // NOI18N
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 60, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48/285653 - enveloppe.png"))); // NOI18N
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 60, 50));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48/285653 - enveloppe.png"))); // NOI18N
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 60, 50));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48/285653 - enveloppe.png"))); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 60, 50));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/48/285653 - enveloppe.png"))); // NOI18N
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 20, 60, 50));

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Person_48px.png"))); // NOI18N
        jLabel1.setText("VISITANTE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 390, 60));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 80));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        panelMenu.setBackground(new java.awt.Color(0, 51, 102));
        panelMenu.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        panelMenu.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        rSButton1.setBackground(new java.awt.Color(0, 51, 102));
        rSButton1.setText("Ver perfil");
        rSButton1.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton1ActionPerformed(evt);
            }
        });
        panelMenu.add(rSButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, -1));

        rSButton2.setBackground(new java.awt.Color(0, 51, 102));
        rSButton2.setText("Consultar libros");
        rSButton2.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton2ActionPerformed(evt);
            }
        });
        panelMenu.add(rSButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, 250, -1));

        rSButton3.setBackground(new java.awt.Color(0, 51, 102));
        rSButton3.setText("Consultar librerías");
        rSButton3.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton3ActionPerformed(evt);
            }
        });
        panelMenu.add(rSButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, -1));

        rSButton4.setBackground(new java.awt.Color(0, 51, 102));
        rSButton4.setText("Consultar editoriales");
        rSButton4.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton4ActionPerformed(evt);
            }
        });
        panelMenu.add(rSButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 250, -1));

        rSButton5.setBackground(new java.awt.Color(0, 51, 102));
        rSButton5.setText("Comprar libro");
        rSButton5.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton5ActionPerformed(evt);
            }
        });
        panelMenu.add(rSButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, -1));

        rSButton6.setBackground(new java.awt.Color(0, 51, 102));
        rSButton6.setText("Quiero ser miembro");
        rSButton6.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton6ActionPerformed(evt);
            }
        });
        panelMenu.add(rSButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 530, 250, -1));

        rSButton7.setBackground(new java.awt.Color(0, 51, 102));
        rSButton7.setText("Cerrar sesión");
        rSButton7.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton7ActionPerformed(evt);
            }
        });
        panelMenu.add(rSButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 570, 250, -1));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(panelMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 610));

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelF.setBackground(new java.awt.Color(255, 255, 255));
        panelF.setLayout(new javax.swing.BoxLayout(panelF, javax.swing.BoxLayout.LINE_AXIS));
        jPanel3.add(panelF, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1010, 610));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 1010, 610));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(56, 0));

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setText("Comando");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        //  jTextField1.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public int X = 110, Y = 100;    int X_V;
    int Y_V;    public void boton7()
    {

        int posicion = panelMenu.getX();

        if (posicion > -1)
        {

            Animacion.Animacion.mover_izquierda(0, -280, 2, 2, panelMenu);

        } else
        {

            Animacion.Animacion.mover_derecha(-280, 0, 2, 2, panelMenu);
        }

    }
    private void boton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boton2ActionPerformed
    {//GEN-HEADEREND:event_boton2ActionPerformed

    }//GEN-LAST:event_boton2ActionPerformed

    private void boton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boton7ActionPerformed
    {//GEN-HEADEREND:event_boton7ActionPerformed

    }//GEN-LAST:event_boton7ActionPerformed
    public void opcionC()
    {
        Color c = JColorChooser.showDialog(rootPane, "ELIGE UN COLOR PARA ENCABEZADOS", jPanel1.getBackground());
        VtnPrincipal.colorPE = c;
        jPanel1.setBackground(VtnPrincipal.colorPE);
    }
    private void boton8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boton8ActionPerformed
    {//GEN-HEADEREND:event_boton8ActionPerformed

    }//GEN-LAST:event_boton8ActionPerformed

    private void boton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boton5ActionPerformed
    {//GEN-HEADEREND:event_boton5ActionPerformed

    }//GEN-LAST:event_boton5ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jButton10ActionPerformed
    {//GEN-HEADEREND:event_jButton10ActionPerformed
        int posicion = panelMenu.getX();

        if (posicion > -1)
        {
            Animacion.Animacion.mover_izquierda(0, -300, 2, 2, panelMenu);
        } else
        {
            Animacion.Animacion.mover_derecha(-300, 0, 2, 2, panelMenu);
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton1ActionPerformed
    {//GEN-HEADEREND:event_rSButton1ActionPerformed
        new CambiaPanel(panelF, new PPerfil(this, nombre_Final_de_Usuario));
    }//GEN-LAST:event_rSButton1ActionPerformed

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton2ActionPerformed
    {//GEN-HEADEREND:event_rSButton2ActionPerformed

    }//GEN-LAST:event_rSButton2ActionPerformed

    private void rSButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton3ActionPerformed
    {//GEN-HEADEREND:event_rSButton3ActionPerformed

    }//GEN-LAST:event_rSButton3ActionPerformed

    private void rSButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton4ActionPerformed
    {//GEN-HEADEREND:event_rSButton4ActionPerformed

    }//GEN-LAST:event_rSButton4ActionPerformed

    private void rSButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton5ActionPerformed
    {//GEN-HEADEREND:event_rSButton5ActionPerformed

    }//GEN-LAST:event_rSButton5ActionPerformed

    private void rSButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton6ActionPerformed
    {//GEN-HEADEREND:event_rSButton6ActionPerformed
        try
        {
            Conexion.con = Conexion.getConexion();
            String sql = "UPDATE t_usuario SET tipo_usuario=? WHERE usuar=?";
            PreparedStatement registro = Conexion.con.prepareStatement(sql);

            String s = "USUARIO";
            String u = nombre_Final_de_Usuario;
            registro.setString(1, s);
            registro.setString(2, u);
            int rh = registro.executeUpdate();

            if (rh > 0)
            {
                JOptionPane.showMessageDialog(null, "Usuario modificado... \n");

                pantallas_Usuario = "USUARIO";

            }
        } catch (SQLException ex)
        {
            Mensaje.errorException(this, "Ha ocurrido un error \n" + ex.toString());
        }
    }//GEN-LAST:event_rSButton6ActionPerformed

    private void rSButton7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton7ActionPerformed
    {//GEN-HEADEREND:event_rSButton7ActionPerformed
        NotificacionSesionCerrada n = new NotificacionSesionCerrada();
        n.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_rSButton7ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt)//GEN-FIRST:event_formWindowOpened
    {//GEN-HEADEREND:event_formWindowOpened
        new CambiaPanel(panelF, new PPerfil(this, nombre_Final_de_Usuario));
    }//GEN-LAST:event_formWindowOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private com.sun.animation.effects.Move move1;
    private javax.swing.JPanel panelF;
    private javax.swing.JPanel panelMenu;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButton rSButton3;
    private rojeru_san.RSButton rSButton4;
    private rojeru_san.RSButton rSButton5;
    private rojeru_san.RSButton rSButton6;
    private rojeru_san.RSButton rSButton7;
    // End of variables declaration//GEN-END:variables
}
