/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VntLibreria;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.sql.Blob;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.table.DefaultTableModel;
import recursos.Mensaje;

/**
 *
 * @author HP
 */
public class VtnConsultarAdministradores extends javax.swing.JFrame
{

    /**
     * Creates new form VtnConsultarAdministradores
     */
    int X_V;
    int Y_V;
    String pantallas_Usuario = "";
    String nombre_Final_de_Usuario = "";

    public VtnConsultarAdministradores(String pantallas_Usuario, String nombre_Final_de_Usuario)
    {
        initComponents();
        jPanel1.setBackground(VtnPrincipal.colorPE);
   Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenesG/buhoAzul.png"));
        setIconImage(icono);
        //   setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        this.setLocationRelativeTo(null);

     

        modeloLista1 = new DefaultListModel();
        modeloLista1.addElement("ID PERSONA");
        modeloLista1.addElement("CLAVE");
        modeloLista1.addElement("NOMBRE");
        modeloLista1.addElement("USUARIO");
        modeloLista1.addElement("APELLIDO PATERNO");
        modeloLista1.addElement("APELLIDO MATERNO");
        modeloLista1.addElement("FECHA DE NACIMIENTO");
        modeloLista1.addElement("DIRECCION");
        modeloLista1.addElement("CORREO ELECTRONICO");
        modeloLista1.addElement("TELEFONO");
        modeloLista1.addElement("TIPO DE USUARIO");
        lista1.setModel(modeloLista1);

        modeloLista2 = new DefaultListModel();
        lista2.setModel(modeloLista2);

        modelo3 = new DefaultComboBoxModel();
        modelo3.addElement("Seleccionar por");
        cbxOrdenar_por.setModel(modelo3);

    }
    DefaultTableModel modelo;
    DefaultListModel modeloLista1;
    DefaultListModel modeloLista2;
    DefaultComboBoxModel modelo3;
    DefaultListModel modeloLista4;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        lista1 = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lista2 = new javax.swing.JList<>();
        cbxOrdenar_por = new javax.swing.JComboBox<>();
        cbxDESC = new javax.swing.JComboBox<>();
        btnQuitar = new javax.swing.JButton();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        rSButton4 = new rojeru_san.RSButton();
        rSButton5 = new rojeru_san.RSButton();
        rSButton6 = new rojeru_san.RSButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jtablaUsuarios = new rojerusan.RSTableMetro();
        jSeparator1 = new javax.swing.JSeparator();
        txtBuscarClave = new rojeru_san.RSMTextFull();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1260, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("CONSULTA PERSONALIZADA DE USUARIOS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 540, 60));

        lista1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lista1.setSelectionBackground(new java.awt.Color(204, 204, 204));
        lista1.setSelectionForeground(new java.awt.Color(0, 0, 0));
        lista1.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lista1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(lista1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, 170, 170));

        lista2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lista2.setSelectionBackground(new java.awt.Color(204, 204, 204));
        lista2.setSelectionForeground(new java.awt.Color(0, 0, 0));
        lista2.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lista2MouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(lista2);

        jPanel1.add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 170, 170));

        cbxOrdenar_por.setBackground(new java.awt.Color(0, 51, 153));
        cbxOrdenar_por.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxOrdenar_por.setOpaque(false);
        cbxOrdenar_por.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                cbxOrdenar_porActionPerformed(evt);
            }
        });
        jPanel1.add(cbxOrdenar_por, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 150, 150, -1));

        cbxDESC.setBackground(new java.awt.Color(0, 51, 153));
        cbxDESC.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cbxDESC.setForeground(new java.awt.Color(255, 255, 255));
        cbxDESC.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ASCENDENTE", "DESCENDENTE" }));
        cbxDESC.setOpaque(false);
        jPanel1.add(cbxDESC, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 150, -1));

        btnQuitar.setBackground(new java.awt.Color(204, 204, 204));
        btnQuitar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnQuitar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118774 - go previous.png"))); // NOI18N
        btnQuitar.setText("Quitar");
        btnQuitar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnQuitarActionPerformed(evt);
            }
        });
        jPanel1.add(btnQuitar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 190, 120, 30));

        btnAgregar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btnAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118773 - go next.png"))); // NOI18N
        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                btnAgregarActionPerformed(evt);
            }
        });
        jPanel1.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 140, 120, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Ordenar por:");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 90, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("De manera:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 90, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Elementos del libro");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 170, 40));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText("Elementos del libro");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 80, 170, 40));

        rSButton4.setBackground(new java.awt.Color(0, 51, 102));
        rSButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118917 - clear edit.png"))); // NOI18N
        rSButton4.setText("Limpiar");
        rSButton4.setColorHover(new java.awt.Color(0, 102, 255));
        rSButton4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 150, 200, -1));

        rSButton5.setBackground(new java.awt.Color(0, 51, 102));
        rSButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px.png"))); // NOI18N
        rSButton5.setText("Regresar");
        rSButton5.setColorHover(new java.awt.Color(0, 102, 255));
        rSButton5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 90, 200, -1));

        rSButton6.setBackground(new java.awt.Color(0, 51, 102));
        rSButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Search_36px_1.png"))); // NOI18N
        rSButton6.setText("Realizar consulta");
        rSButton6.setColorHover(new java.awt.Color(0, 102, 255));
        rSButton6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(1030, 210, 200, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Buscar por nombre del Libro:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 160, 230, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(153, 153, 153));
        jLabel6.setText("*VISTA PRETERMINADA");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 90, 210, 30));

        jtablaUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID de usuario", "Clave", "Usuario", "Nombre(S)", "Apellido Materno", "Apellido Paterno", "Foto de perfil"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jtablaUsuarios.setColorBackgoundHead(new java.awt.Color(0, 51, 102));
        jtablaUsuarios.setColorBordeFilas(new java.awt.Color(204, 204, 204));
        jtablaUsuarios.setColorBordeHead(new java.awt.Color(204, 204, 204));
        jtablaUsuarios.setColorFilasForeground1(new java.awt.Color(0, 0, 51));
        jtablaUsuarios.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        jtablaUsuarios.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane4.setViewportView(jtablaUsuarios);
        if (jtablaUsuarios.getColumnModel().getColumnCount() > 0)
        {
            jtablaUsuarios.getColumnModel().getColumn(0).setResizable(false);
            jtablaUsuarios.getColumnModel().getColumn(3).setResizable(false);
            jtablaUsuarios.getColumnModel().getColumn(4).setResizable(false);
            jtablaUsuarios.getColumnModel().getColumn(5).setResizable(false);
        }

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 320, 1200, 230));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 51));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 90, 30, 200));

        txtBuscarClave.setForeground(new java.awt.Color(0, 51, 102));
        txtBuscarClave.setBordeColorFocus(new java.awt.Color(0, 51, 102));
        txtBuscarClave.setBotonColor(new java.awt.Color(0, 51, 102));
        txtBuscarClave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtBuscarClave.setOpaque(false);
        txtBuscarClave.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtBuscarClaveKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 200, 210, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void agregarLista()
    {
        if (lista1.getSelectedIndex() == -1)
        {
            //mesaje de que seleciones
        } else
        {
            String s = lista1.getSelectedValue();
            modeloLista1.removeElementAt(lista1.getSelectedIndex());
            modeloLista2.addElement(s);
            modelo3.addElement(s);
        }
    }

    public void quitarLista()
    {

        if (lista2.getSelectedIndex() == -1)
        {
//mensaje
        } else
        {
            String s = lista2.getSelectedValue();

            modeloLista2.removeElementAt(lista2.getSelectedIndex());
            modeloLista1.addElement(s);
            modelo3.removeElement(s);
        }
    }

    public void lista1MauseClicked()
    {
        btnQuitar.setEnabled(false);
        btnAgregar.setEnabled(true);
    }

    public void lista2Mauseclick()
    {
        btnQuitar.setEnabled(true);
        btnAgregar.setEnabled(false);
    }
    private void boton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boton1ActionPerformed
    {//GEN-HEADEREND:event_boton1ActionPerformed

    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boton2ActionPerformed
    {//GEN-HEADEREND:event_boton2ActionPerformed

    }//GEN-LAST:event_boton2ActionPerformed

    private void lista1MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lista1MouseClicked
    {//GEN-HEADEREND:event_lista1MouseClicked
        btnQuitar.setEnabled(false);
        btnAgregar.setEnabled(true);
    }//GEN-LAST:event_lista1MouseClicked

    private void lista2MouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lista2MouseClicked
    {//GEN-HEADEREND:event_lista2MouseClicked
        btnQuitar.setEnabled(true);
        btnAgregar.setEnabled(false);
    }//GEN-LAST:event_lista2MouseClicked

    private void cbxOrdenar_porActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_cbxOrdenar_porActionPerformed
    {//GEN-HEADEREND:event_cbxOrdenar_porActionPerformed

    }//GEN-LAST:event_cbxOrdenar_porActionPerformed

    private void btnQuitarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnQuitarActionPerformed
    {//GEN-HEADEREND:event_btnQuitarActionPerformed

        if (lista2.getSelectedIndex() == -1)
        {
            //mensaje
        } else
        {
            String s = lista2.getSelectedValue();

            modeloLista2.removeElementAt(lista2.getSelectedIndex());
            modeloLista1.addElement(s);
            modelo3.removeElement(s);
        }
    }//GEN-LAST:event_btnQuitarActionPerformed

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_btnAgregarActionPerformed
    {//GEN-HEADEREND:event_btnAgregarActionPerformed
        if (lista1.getSelectedIndex() == -1)
        {
            //mesaje de que seleciones
        } else
        {
            String s = lista1.getSelectedValue();
            modeloLista1.removeElementAt(lista1.getSelectedIndex());
            modeloLista2.addElement(s);
            modelo3.addElement(s);
        }
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void rSButton4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton4ActionPerformed
    {//GEN-HEADEREND:event_rSButton4ActionPerformed
        modeloLista1 = new DefaultListModel();
        modeloLista1.addElement("ID PERSONA");
        modeloLista1.addElement("CLAVE");
        modeloLista1.addElement("NOMBRE");
        modeloLista1.addElement("USUARIO");
        modeloLista1.addElement("APELLIDO PATERNO");
        modeloLista1.addElement("APELLIDO MATERNO");
        modeloLista1.addElement("FECHA DE NACIMIENTO");
        modeloLista1.addElement("DIRECCION");
        modeloLista1.addElement("CORREO ELECTRONICO");
        modeloLista1.addElement("TELEFONO");
        modeloLista1.addElement("TIPO DE USUARIO");
        lista1.setModel(modeloLista1);

        modeloLista2 = new DefaultListModel();
        lista2.setModel(modeloLista2);

        modelo3 = new DefaultComboBoxModel();
        modelo3.addElement("Seleccionar por");
        cbxOrdenar_por.setModel(modelo3);
    }//GEN-LAST:event_rSButton4ActionPerformed

    private void rSButton5ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton5ActionPerformed
    {//GEN-HEADEREND:event_rSButton5ActionPerformed
        CtrComponentes.botonSalirSI(this, nombre_Final_de_Usuario, pantallas_Usuario);
    }//GEN-LAST:event_rSButton5ActionPerformed

    private void rSButton6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton6ActionPerformed
    {//GEN-HEADEREND:event_rSButton6ActionPerformed
        btn2();
    }//GEN-LAST:event_rSButton6ActionPerformed

    private void txtBuscarClaveKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtBuscarClaveKeyReleased
    {//GEN-HEADEREND:event_txtBuscarClaveKeyReleased
        mostrarDatos(txtBuscarClave.getText().trim());
    }//GEN-LAST:event_txtBuscarClaveKeyReleased
    public void btn2()
    {
        int tE = modeloLista2.getSize();
        if (tE == 0)
        {
            mostrarDatos(txtBuscarClave.getText().toUpperCase().trim());
        } else
        {
            if (cbxOrdenar_por.getSelectedItem().equals("Seleccionar por"))
            {
                int tElementos = modeloLista2.getSize();
                String[] elementosT = new String[tElementos];
                for (int i = 0; i < tElementos; i++)
                {
                    elementosT[i] = (String) modeloLista2.getElementAt(i);
                }
                muestraConsultaPersonalizada(elementosT);
            } else
            {
                int tElementos = modeloLista2.getSize();
                String[] elementosT = new String[tElementos];
                for (int i = 0; i < tElementos; i++)
                {
                    elementosT[i] = (String) modeloLista2.getElementAt(i);
                }
                String ordenarPor = modelo3.getElementAt(cbxOrdenar_por.getSelectedIndex()).toString();
                if ("ID PERSONA".equals(ordenarPor))
                {
                    ordenarPor = "id_usu";
                }
                if ("CLAVE".equals(ordenarPor))
                {
                    ordenarPor = "clave_usu";
                }
                if ("USUARIO".equals(ordenarPor))
                {
                    ordenarPor = "usuar";
                }
                if ("NOMBRE".equals(ordenarPor))
                {
                    ordenarPor = "nombre_usu";
                }
                if ("APELLIDO PATERNO".equals(ordenarPor))
                {
                    ordenarPor = "apellido_paterno_usu";
                }
                if ("APELLIDO MATERNO".equals(ordenarPor))
                {
                    ordenarPor = "apellido_materno_usu";
                }
                if ("FECHA DE NACIMIENTO".equals(ordenarPor))
                {
                    ordenarPor = "fecha_de_nacimiento_usu";
                }
                if ("DIRECCION".equals(ordenarPor))
                {
                    ordenarPor = "dir_usu";
                }
                if ("CORREO ELECTRONICO".equals(ordenarPor))
                {
                    ordenarPor = "email_usu";
                }
                if ("TELEFONO".equals(ordenarPor))
                {
                    ordenarPor = "cel_usu";
                }
                if ("TIPO DE USUARIO".equals(ordenarPor))
                {
                    ordenarPor = "tipo_usuario";
                }

                if (cbxDESC.getSelectedItem().equals("ASCENDENTE"))
                {

                    muestraConsultaPersonalizadaConOrdenPor(elementosT, ordenarPor, "ASCENDENTE");
                } else
                {

                    muestraConsultaPersonalizadaConOrdenPor(elementosT, ordenarPor, "DESCENDENTE");
                }

            }
        }
    }

    void mostrarDatos(String clave)
    {

        jtablaUsuarios.setDefaultRenderer(Object.class, new Tabla());
        modelo = new DefaultTableModel();
        modelo.addColumn("ID USUARIO");
        modelo.addColumn("CLAVE");
        modelo.addColumn("USUARIO");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("APELLIDO PATERNO");
        modelo.addColumn("APELLIDO MATERNO");
        modelo.addColumn("FOTO DE PERFIL");

        jtablaUsuarios.setModel(modelo);
        jtablaUsuarios.setEnabled(false);

        String sql = "";
        if (clave.equals(""))
        {
            sql = "SELECT * FROM t_persona";
        } else
        {

            sql = "SELECT * FROM t_persona WHERE clave_usu like '" + clave + "%'";

        }

        Object datos[] = new Object[7];
        Statement st;
        Conexion.con = Conexion.getConexion();
        try
        {
            st = Conexion.con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
                datos[0] = rs.getString("id_usu");
                datos[1] = rs.getString("clave_usu");
                datos[2] = rs.getString("usuar");
                datos[3] = rs.getString("nombre_usu");
                datos[4] = rs.getString("apellido_paterno_usu");
                datos[5] = rs.getString("apellido_materno_usu");
                Blob blob = rs.getBlob("foto_perfil_usu");
                byte[] data = blob.getBytes(1, (int) blob.length());
                BufferedImage img = null;
                try
                {
                    img = ImageIO.read(new ByteArrayInputStream(data));
                } catch (IOException e)
                {
                    Mensaje.errorException(this, "Ha ocurrido un error \n" + e.toString());
                }
                ImageIcon icono = new ImageIcon(img);
                JLabel u = new JLabel();
                u.setIcon(new ImageIcon(icono.getImage()
                        .getScaledInstance(70, 100, Image.SCALE_SMOOTH)));
                datos[6] = u;
                modelo.addRow(datos);
            }
            jtablaUsuarios.setRowHeight(100);
            jtablaUsuarios.setModel(modelo);
        } catch (SQLException e)
        {
            Mensaje.errorException(this, "Ha ocurrido un error \n" + e.toString());
        }

    }
    // int anchos[]={10,250,250,25};
    // for (int x = 0; x < jTablaUsuarios.getColumnCount(); x++)
    // {
    // jTablaUsuarios.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
    //}

    public void muestraConsultaPersonalizada(String camposT[])
    {
        try
        {
            modelo = new DefaultTableModel();
            String sql = "SELECT * FROM t_persona";
            Statement st;
            Conexion.con = Conexion.getConexion();
            st = Conexion.con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
                Conexion.con = Conexion.getConexion();
                st = Conexion.con.createStatement();
                rs = st.executeQuery(sql);
                ingresaCamposT(0, rs, camposT, "");
            }

        } catch (SQLException e)
        {
            Mensaje.errorException(this, "Ha ocurrido un error \n" + e.toString());
        }
    }

    public void muestraConsultaPersonalizadaConOrdenPor(String camposT[], String ordenarPor, String desde)
    {
        if (desde.equals("ASCENDENTE"))
        {
            try
            {

                modelo = new DefaultTableModel();
                String sql = "SELECT * FROM t_persona order by " + ordenarPor + "";
                Statement st;
                Conexion.con = Conexion.getConexion();
                st = Conexion.con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next())
                {
                    Conexion.con = Conexion.getConexion();
                    st = Conexion.con.createStatement();
                    rs = st.executeQuery(sql);
                    ingresaCamposT(0, rs, camposT, ordenarPor);
                }

            } catch (SQLException e)
            {
                Mensaje.errorException(this, "Ha ocurrido un error \n" + e.toString());
            }
        } else
        {
            try
            {

                modelo = new DefaultTableModel();
                String sql = "SELECT * FROM t_persona order by " + ordenarPor + " DESC";
                Statement st;
                Conexion.con = Conexion.getConexion();
                st = Conexion.con.createStatement();
                ResultSet rs = st.executeQuery(sql);
                while (rs.next())
                {
                    Conexion.con = Conexion.getConexion();
                    st = Conexion.con.createStatement();
                    rs = st.executeQuery(sql);
                    ingresaCamposT(1, rs, camposT, ordenarPor);
                }

            } catch (SQLException e)
            {
                Mensaje.errorException(this, "Ha ocurrido un error \n" + e.toString());
            }
        }

    }

    public void ingresaCamposT(int i, ResultSet rs, String campos[], String orden)
    {
        if (i == 0)
        {
            try
            {

                for (int j = 0; j < campos.length; j++)
                {
                    modelo.addColumn(campos[j]);

                }
                jtablaUsuarios.setModel(modelo);

                String camposSQL[] = new String[campos.length];
                boolean consultaJoin = false;
                for (int j = 0; j < campos.length; j++)
                {
                    if ("ID PERSONA".equals(campos[j]))
                    {
                        camposSQL[j] = "id_usu";
                    }
                    if ("CLAVE".equals(campos[j]))
                    {
                        camposSQL[j] = "clave_usu";
                    }
                    if ("USUARIO".equals(campos[j]))
                    {
                        camposSQL[j] = "usuar";
                    }
                    if ("NOMBRE".equals(campos[j]))
                    {
                        camposSQL[j] = "nombre_usu";
                    }
                    if ("APELLIDO PATERNO".equals(campos[j]))
                    {
                        camposSQL[j] = "apellido_paterno_usu";
                    }
                    if ("APELLIDO MATERNO".equals(campos[j]))
                    {
                        camposSQL[j] = "apellido_materno_usu";
                    }
                    if ("FECHA DE NACIMIENTO".equals(campos[j]))
                    {
                        camposSQL[j] = "fecha_de_nacimiento_usu";
                    }
                    if ("DIRECCION".equals(campos[j]))
                    {
                        camposSQL[j] = "dir_usu";
                    }
                    if ("CORREO ELECTRONICO".equals(campos[j]))
                    {
                        camposSQL[j] = "email_usu";
                    }
                    if ("TELEFONO".equals(campos[j]))
                    {
                        camposSQL[j] = "cel_usu";
                    }
                    if ("TIPO DE USUARIO".equals(campos[j]))
                    {
                        camposSQL[j] = "tipo_usuario";
                        consultaJoin = true;
                    }

                }
                if (consultaJoin == false)
                {

                    String datos[] = new String[campos.length];

                    int index = 0;
                    while (rs.next())
                    {
                        for (int j = 0; j < campos.length; j++)
                        {
                            try
                            {
                                datos[index] = rs.getString(camposSQL[j]);
                                index++;
                            } catch (SQLException ex)
                            {
                                Mensaje.errorException(this, "Ha ocurrido un error \n" + ex.toString());
                            }
                        }
                        modelo.addRow(datos);
                        jtablaUsuarios.setModel(modelo);
                        index = 0;
                    }
                } else
                {
                    String datos[] = new String[campos.length];

                    int index = 0;
                    while (rs.next())
                    {
                        for (int j = 0; j < campos.length; j++)
                        {
                            try
                            {
                                if ("tipo_usuario".equals(camposSQL[j]))
                                {
                                    Conexion.con = Conexion.getConexion();
                                    PreparedStatement ps1 = Conexion.con.prepareStatement("SELECT tipo_usuario FROM usuario where usuar=?");
                                    String usuario = rs.getString("usuar");

                                    ps1.setString(1, usuario);
                                    ResultSet rs1;
                                    rs1 = ps1.executeQuery();
                                    if (rs1.next())
                                    {
                                        datos[index] = rs1.getString("tipo_usuario");
                                        index++;
                                    } else
                                    {
                                        datos[index] = "NO";
                                        index++;
                                    }

                                } else
                                {
                                    datos[index] = rs.getString(camposSQL[j]);
                                    index++;
                                }

                            } catch (SQLException ex)
                            {
                                Mensaje.errorException(this, "Ha ocurrido un error \n" + ex.toString());
                            }
                        }
                        modelo.addRow(datos);
                        jtablaUsuarios.setModel(modelo);
                        index = 0;
                    }
                }

            } catch (SQLException ex)
            {
                Mensaje.errorException(this, "Ha ocurrido un error \n" + ex.toString());
            }
        } else
        {
            try
            {

                for (int j = 0; j < campos.length; j++)
                {
                    modelo.addColumn(campos[j]);

                }
                jtablaUsuarios.setModel(modelo);

                String camposSQL[] = new String[campos.length];
                boolean consultaJoin = false;
                for (int j = 0; j < campos.length; j++)
                {
                    if ("ID PERSONA".equals(campos[j]))
                    {
                        camposSQL[j] = "id_usu";
                    }
                    if ("CLAVE".equals(campos[j]))
                    {
                        camposSQL[j] = "clave_usu";
                    }
                    if ("USUARIO".equals(campos[j]))
                    {
                        camposSQL[j] = "usuar";
                    }
                    if ("NOMBRE".equals(campos[j]))
                    {
                        camposSQL[j] = "nombre_usu";
                    }
                    if ("APELLIDO PATERNO".equals(campos[j]))
                    {
                        camposSQL[j] = "apellido_paterno_usu";
                    }
                    if ("APELLIDO MATERNO".equals(campos[j]))
                    {
                        camposSQL[j] = "apellido_materno_usu";
                    }
                    if ("FECHA DE NACIMIENTO".equals(campos[j]))
                    {
                        camposSQL[j] = "fecha_de_nacimiento_usu";
                    }
                    if ("DIRECCION".equals(campos[j]))
                    {
                        camposSQL[j] = "dir_usu";
                    }
                    if ("CORREO ELECTRONICO".equals(campos[j]))
                    {
                        camposSQL[j] = "email_usu";
                    }
                    if ("TELEFONO".equals(campos[j]))
                    {
                        camposSQL[j] = "cel_usu";
                    }
                    if ("TIPO DE USUARIO".equals(campos[j]))
                    {
                        camposSQL[j] = "tipo_usuario";
                        consultaJoin = true;
                    }

                }
                if (consultaJoin == false)
                {
                    String datos[] = new String[campos.length];

                    int index = 0;
                    while (rs.next())
                    {
                        for (int j = 0; j < campos.length; j++)
                        {
                            try
                            {
                                datos[index] = rs.getString(camposSQL[j]);
                                index++;
                            } catch (SQLException ex)
                            {
                                Mensaje.errorException(this, "Ha ocurrido un error \n" + ex.toString());
                            }
                        }
                        modelo.addRow(datos);
                        jtablaUsuarios.setModel(modelo);
                        index = 0;
                    }
                } else
                {

                    String datos[] = new String[campos.length];

                    int index = 0;
                    while (rs.next())
                    {
                        for (int j = 0; j < campos.length; j++)
                        {
                            try
                            {
                                if ("tipo_usuario".equals(camposSQL[j]))
                                {
                                    Conexion.con = Conexion.getConexion();
                                    PreparedStatement ps1 = Conexion.con.prepareStatement("SELECT tipo_usuario FROM t_usuario where usuar=?");
                                    String usuario = rs.getString("usuar");

                                    ps1.setString(1, usuario);
                                    ResultSet rs1;
                                    rs1 = ps1.executeQuery();
                                    if (rs1.next())
                                    {
                                        datos[index] = rs1.getString("tipo_usuario");
                                        index++;
                                    } else
                                    {
                                        datos[index] = "NO";
                                        index++;
                                    }

                                } else
                                {
                                    datos[index] = rs.getString(camposSQL[j]);
                                    index++;
                                }

                            } catch (SQLException ex)
                            {
                                Mensaje.errorException(this, "Ha ocurrido un error \n" + ex.toString());
                            } finally
                            {
                                try
                                {
                                    Conexion.con.close();
                                } catch (SQLException ex)
                                {
                                    Mensaje.errorException(this, "Ha ocurrido un error \n" + ex.toString());
                                }
                            }
                        }
                        modelo.addRow(datos);
                        jtablaUsuarios.setModel(modelo);
                        index = 0;
                    }
                }

            } catch (SQLException ex)
            {
                Mensaje.errorException(this, "Ha ocurrido un error \n" + ex.toString());
            }
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnQuitar;
    private javax.swing.JComboBox<String> cbxDESC;
    private javax.swing.JComboBox<String> cbxOrdenar_por;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private rojerusan.RSTableMetro jtablaUsuarios;
    private javax.swing.JList<String> lista1;
    private javax.swing.JList<String> lista2;
    private rojeru_san.RSButton rSButton4;
    private rojeru_san.RSButton rSButton5;
    private rojeru_san.RSButton rSButton6;
    private rojeru_san.RSMTextFull txtBuscarClave;
    // End of variables declaration//GEN-END:variables
}
