/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VntLibreria;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Color;
import java.awt.Font;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.awt.MouseInfo;
import java.awt.Point;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.InputStream;
import java.sql.Blob;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import recursos.Mensaje;

/**
 *
 * @author HP
 */
public class VtnConsultarLibros extends javax.swing.JFrame
{

    /**
     * Creates new form VtnConsultarLibros
     */
    int X_V;
    int Y_V;
    String pantallas_Usuario = "";
    String nombre_Final_de_Usuario = "";

    public VtnConsultarLibros(String pantallas_Usuario, String nombre_Final_de_Usuario)
    {
        this.nombre_Final_de_Usuario = nombre_Final_de_Usuario;
        this.pantallas_Usuario = pantallas_Usuario;
        initComponents();
         Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenesG/buhoAzul.png"));
        setIconImage(icono);
        //   setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        this.setLocationRelativeTo(null);

     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        rSButton2 = new rojeru_san.RSButton();
        rSButton3 = new rojeru_san.RSButton();
        txtBuscarClave = new rojeru_san.RSMTextFull();

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu1.add(jMenuItem1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1260, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel4.setText("CONSULTA DE LIBROS");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 400, 60));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel5.setText("Buscar:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 140, 60, -1));

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 102)));
        jPanel3.setLayout(new java.awt.GridLayout(0, 4, 5, 5));
        jScrollPane4.setViewportView(jPanel3);

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 1240, 420));

        rSButton2.setBackground(new java.awt.Color(0, 51, 102));
        rSButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px.png"))); // NOI18N
        rSButton2.setText("Regresar");
        rSButton2.setColorHover(new java.awt.Color(0, 102, 255));
        rSButton2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 110, 160, -1));

        rSButton3.setBackground(new java.awt.Color(0, 51, 102));
        rSButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Search_31px.png"))); // NOI18N
        rSButton3.setText("Consultar");
        rSButton3.setColorHover(new java.awt.Color(0, 102, 255));
        rSButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 110, 160, -1));

        txtBuscarClave.setForeground(new java.awt.Color(0, 51, 102));
        txtBuscarClave.setBordeColorFocus(new java.awt.Color(0, 51, 102));
        txtBuscarClave.setBotonColor(new java.awt.Color(0, 51, 102));
        txtBuscarClave.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtBuscarClave.setOpaque(false);
        txtBuscarClave.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtBuscarClaveKeyReleased(evt);
            }
        });
        jPanel1.add(txtBuscarClave, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 250, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 610));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public JPanel componenetesRecomendacion(javax.swing.JPanel v, String nomreLibro, String autorLibro, String editorial)
    {
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel panelRecomienda = new javax.swing.JPanel();
        javax.swing.JLabel etirquetaTituloLibro1 = new javax.swing.JLabel();
        javax.swing.JLabel etiquetaAutorLibro1 = new javax.swing.JLabel();
        javax.swing.JLabel etiquetaEditorial1 = new javax.swing.JLabel();
        javax.swing.JLabel etiqueta4 = new javax.swing.JLabel();
        javax.swing.JLabel etiqueta5 = new javax.swing.JLabel();
        javax.swing.JLabel etiqueta6 = new javax.swing.JLabel();
        javax.swing.JPanel panelImagenRecomienda = new javax.swing.JPanel();
        rojeru_san.RSButton bntDescripcion1 = new rojeru_san.RSButton();
        javax.swing.JCheckBox jCheckBox1 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox2 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox3 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox4 = new javax.swing.JCheckBox();
        javax.swing.JCheckBox jCheckBox5 = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelRecomienda.setBackground(new java.awt.Color(255, 255, 255));
        panelRecomienda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));

        panelRecomienda.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                if (jCheckBox1.isSelected())
                {
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                } else if (jCheckBox2.isSelected())
                {
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                } else if (jCheckBox3.isSelected())
                {
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                } else if (jCheckBox4.isSelected())
                {
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                } else if (jCheckBox5.isSelected())
                {

                } else
                {
                    jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                }

            }
        });
        panelRecomienda.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etirquetaTituloLibro1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        //Nombre del libro
        etirquetaTituloLibro1.setText(nomreLibro);
        panelRecomienda.add(etirquetaTituloLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 150, -1));

        etiquetaAutorLibro1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        //Autor del Libro
        etiquetaAutorLibro1.setText(autorLibro);
        panelRecomienda.add(etiquetaAutorLibro1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 160, 20));

        etiquetaEditorial1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        //Editorial del libro
        etiquetaEditorial1.setText(editorial);
        panelRecomienda.add(etiquetaEditorial1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 170, -1));

        etiqueta4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiqueta4.setForeground(new java.awt.Color(102, 102, 102));
        etiqueta4.setText("Nombre del libro:");
        panelRecomienda.add(etiqueta4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        etiqueta5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiqueta5.setForeground(new java.awt.Color(102, 102, 102));
        etiqueta5.setText("Autor:");
        panelRecomienda.add(etiqueta5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 40, -1));

        etiqueta6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiqueta6.setForeground(new java.awt.Color(102, 102, 102));
        etiqueta6.setText("Editorial:");
        panelRecomienda.add(etiqueta6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, -1));

        javax.swing.GroupLayout panelImagenRecomiendaLayout = new javax.swing.GroupLayout(panelImagenRecomienda);
        panelImagenRecomienda.setLayout(panelImagenRecomiendaLayout);
        panelImagenRecomiendaLayout.setHorizontalGroup(
                panelImagenRecomiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 130, Short.MAX_VALUE)
        );
        panelImagenRecomiendaLayout.setVerticalGroup(
                panelImagenRecomiendaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 150, Short.MAX_VALUE)
        );

        panelRecomienda.add(panelImagenRecomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));

        bntDescripcion1.setBackground(new java.awt.Color(0, 51, 102));
        bntDescripcion1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Up_24px.png"))); // NOI18N
        bntDescripcion1.setText("Ver descripción");
        bntDescripcion1.setColorHover(new java.awt.Color(0, 102, 204));

        bntDescripcion1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                /*
                Que se desea hacer una vez que se oprima el boton
                 */
                nombre_libro_s = etirquetaTituloLibro1.getText();
                ProductInformationLibro ps = new ProductInformationLibro(nombre_libro_s);
                ps.setVisible(true);
            }
        });
        panelRecomienda.add(bntDescripcion1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 310, -1));

        jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png"))); // NOI18N
        jCheckBox1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star.png"))); // NOI18N
        jCheckBox1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png"))); // NOI18N
        jCheckBox1.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (2).png"))); // NOI18N

        jCheckBox1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                if (!(jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected()))
                {
                    jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                }
            }
        });

        jCheckBox1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(false);
                jCheckBox3.setSelected(false);
                jCheckBox4.setSelected(false);
                jCheckBox5.setSelected(false);
                jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
            }
        });
        panelRecomienda.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, 30));

        jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png"))); // NOI18N
        jCheckBox2.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star.png"))); // NOI18N
        jCheckBox2.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png"))); // NOI18N
        jCheckBox2.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (2).png"))); // NOI18N

        jCheckBox2.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                if (!(jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected()))
                {
                    jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));

                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                }
            }
        });

        jCheckBox2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {

                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(true);
                jCheckBox3.setSelected(false);
                jCheckBox4.setSelected(false);
                jCheckBox5.setSelected(false);
                jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));

            }
        });
        panelRecomienda.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, -1, 30));

        jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png"))); // NOI18N
        jCheckBox3.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star.png"))); // NOI18N
        jCheckBox3.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png"))); // NOI18N
        jCheckBox3.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (2).png"))); // NOI18N

        jCheckBox3.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                if (!(jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected()))
                {
                    jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));

                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                }
            }
        });

        jCheckBox3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(true);
                jCheckBox3.setSelected(true);
                jCheckBox4.setSelected(false);
                jCheckBox5.setSelected(false);
                jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
            }
        });
        panelRecomienda.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, 30));

        jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png"))); // NOI18N
        jCheckBox4.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star.png"))); // NOI18N
        jCheckBox4.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png"))); // NOI18N
        jCheckBox4.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (2).png"))); // NOI18N

        jCheckBox4.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                if (!(jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected()))
                {
                    jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));

                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
                }
            }
        });

        jCheckBox4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(true);
                jCheckBox3.setSelected(true);
                jCheckBox4.setSelected(true);
                jCheckBox5.setSelected(false);
                jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png")));
            }
        });
        panelRecomienda.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, -1, 30));

        jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (4).png"))); // NOI18N
        jCheckBox5.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star.png"))); // NOI18N
        jCheckBox5.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png"))); // NOI18N
        jCheckBox5.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (2).png"))); // NOI18N

        jCheckBox5.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                if (!(jCheckBox1.isSelected() && jCheckBox2.isSelected() && jCheckBox3.isSelected() && jCheckBox4.isSelected() && jCheckBox5.isSelected()))
                {
                    jCheckBox1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));
                    jCheckBox5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/icon-23-star (3).png")));

                }
            }
        });

        jCheckBox5.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBox1.setSelected(true);
                jCheckBox2.setSelected(true);
                jCheckBox3.setSelected(true);
                jCheckBox4.setSelected(true);
                jCheckBox5.setSelected(true);
            }
        });
        panelRecomienda.add(jCheckBox5, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 270, -1, 30));
        v.add(panelRecomienda, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 360));
        return panelImagenRecomienda;
    }
    private void boton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boton1ActionPerformed
    {//GEN-HEADEREND:event_boton1ActionPerformed

    }//GEN-LAST:event_boton1ActionPerformed

    private void boton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_boton2ActionPerformed
    {//GEN-HEADEREND:event_boton2ActionPerformed


    }//GEN-LAST:event_boton2ActionPerformed
    String nombre_libro_s = "";
    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed

    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void rSButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton3ActionPerformed
    {//GEN-HEADEREND:event_rSButton3ActionPerformed
        mostrarDatos(txtBuscarClave.getText().toUpperCase().trim());
    }//GEN-LAST:event_rSButton3ActionPerformed

    private void rSButton2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton2ActionPerformed
    {//GEN-HEADEREND:event_rSButton2ActionPerformed
        CtrComponentes.botonSalirSI(this, nombre_Final_de_Usuario, pantallas_Usuario);
    }//GEN-LAST:event_rSButton2ActionPerformed

    private void txtBuscarClaveKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtBuscarClaveKeyReleased
    {//GEN-HEADEREND:event_txtBuscarClaveKeyReleased
        mostrarDatos(txtBuscarClave.getText().toUpperCase().trim());
    }//GEN-LAST:event_txtBuscarClaveKeyReleased

    public void btnmuestr()
    {
        mostrarDatos(txtBuscarClave.getText().toUpperCase().trim());

    }

    void mostrarDatos(String clave)
    {

        String sql = "";
        if (clave.equals(""))
        {
            sql = "SELECT * FROM t_libro";
            jPanel3.removeAll();
        } else
        {

            sql = "SELECT * FROM t_libro WHERE nombre_libro like '%" + clave + "%' OR autor_libro like '%" + clave + "%' OR editorial_libro like '%" + clave + "%'";
            jPanel3.removeAll();

        }

        Statement st;
        Conexion.con = Conexion.getConexion();
        try
        {
            st = Conexion.con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {

                JPanel v = new JPanel();
                v.setBackground(Color.white);
                String nombreLibro = rs.getString("nombre_libro");
                String autorLibro = rs.getString("autor_libro");
                String editorial = rs.getString("editorial_libro");
                 JPanel panelImagen = componentesReacciona(v, nombreLibro, autorLibro, editorial);
                //JPanel panelImagen = componenetesRecomendacion(v, nombreLibro, autorLibro, editorial);

                Blob blob = rs.getBlob("portada");
                byte[] data = blob.getBytes(1, (int) blob.length());
                BufferedImage img = null;
                try
                {
                    img = ImageIO.read(new ByteArrayInputStream(data));
                } catch (Exception e)
                {
                    Mensaje.errorException(this, "Ha ocurrido un error \n" + e.toString());
                }

                ImageIcon icono = new ImageIcon(img);
                javax.swing.JLabel imagenPortada = new javax.swing.JLabel();
                imagenPortada.setBounds(0, 0, 130, 150);
                imagenPortada.setIcon(new ImageIcon(icono.getImage().getScaledInstance(130, 150, Image.SCALE_SMOOTH)));
                imagenPortada.setVisible(true);
                panelImagen.add(imagenPortada);
                jPanel3.add(v);
                jPanel3.updateUI();

            }

        } catch (SQLException e)
        {
            Mensaje.errorException(this, "Ha ocurrido un error \n" + e.toString());
        }

    }

    public JPanel componentesReacciona(javax.swing.JPanel v, String nomreLibro, String autorLibro, String editorial)
    {
        javax.swing.ButtonGroup buttonGroup1 = new javax.swing.ButtonGroup();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JPanel panelReaccion = new javax.swing.JPanel();
        javax.swing.JLabel etirquetaTituloLibro = new javax.swing.JLabel();
        javax.swing.JLabel etiquetaAutorLibro = new javax.swing.JLabel();
        javax.swing.JLabel etiquetaEditorial = new javax.swing.JLabel();
        javax.swing.JLabel etiqueta1 = new javax.swing.JLabel();
        javax.swing.JLabel etiqueta2 = new javax.swing.JLabel();
        javax.swing.JLabel etiqueta3 = new javax.swing.JLabel();
        javax.swing.JPanel panelVerificarReaccion = new javax.swing.JPanel();
        javax.swing.JPanel panelEmocion = new javax.swing.JPanel();
        org.edisoncor.gui.panel.PanelLlamada panelLlamadaEmocion = new org.edisoncor.gui.panel.PanelLlamada();
        javax.swing.JRadioButton radioEncanta = new javax.swing.JRadioButton();
        javax.swing.JRadioButton radioSonroja = new javax.swing.JRadioButton();
        javax.swing.JRadioButton radioAsombra = new javax.swing.JRadioButton();
        javax.swing.JRadioButton radioDivierte = new javax.swing.JRadioButton();
        javax.swing.JRadioButton radioEntristece = new javax.swing.JRadioButton();
        javax.swing.JRadioButton radioEnoja = new javax.swing.JRadioButton();
        javax.swing.JRadioButton radioGusta = new javax.swing.JRadioButton();
        javax.swing.JToggleButton botonEmocion = new javax.swing.JToggleButton();
        javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JPanel jPanelImagem = new javax.swing.JPanel();
        rojeru_san.RSButton bntDescripcion = new rojeru_san.RSButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelReaccion.setBackground(new java.awt.Color(255, 255, 255));
        panelReaccion.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 51)));
        panelReaccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        etirquetaTituloLibro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        //Nombre del Libro
        etirquetaTituloLibro.setText(nomreLibro);
        panelReaccion.add(etirquetaTituloLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 150, -1));

        etiquetaAutorLibro.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        //Autor del libro
        etiquetaAutorLibro.setText(autorLibro);
        panelReaccion.add(etiquetaAutorLibro, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 220, 160, 20));

        etiquetaEditorial.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        //Editorial del libro
        etiquetaEditorial.setText(editorial);
        panelReaccion.add(etiquetaEditorial, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, 170, -1));

        etiqueta1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiqueta1.setForeground(new java.awt.Color(102, 102, 102));
        etiqueta1.setText("Nombre del libro:");
        panelReaccion.add(etiqueta1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 190, -1, -1));

        etiqueta2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiqueta2.setForeground(new java.awt.Color(102, 102, 102));
        etiqueta2.setText("Autor:");
        panelReaccion.add(etiqueta2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 40, -1));

        etiqueta3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        etiqueta3.setForeground(new java.awt.Color(102, 102, 102));
        etiqueta3.setText("Editorial:");
        panelReaccion.add(etiqueta3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 80, -1));

        panelVerificarReaccion.setOpaque(false);
        panelVerificarReaccion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                panelLlamadaEmocion.setVisible(false);
            }
        });
        panelVerificarReaccion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelEmocion.setOpaque(false);

        panelEmocion.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                panelLlamadaEmocion.setVisible(false);
                reacciona(radioEncanta, radioSonroja, radioAsombra, radioDivierte, radioEntristece, radioEnoja, radioGusta, botonEmocion, panelLlamadaEmocion);
            }
        });
        panelEmocion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelLlamadaEmocion.setColorDeBorde(new java.awt.Color(153, 153, 153));
        panelLlamadaEmocion.setColorPrimario(new java.awt.Color(255, 255, 255));
        panelLlamadaEmocion.setColorSecundario(new java.awt.Color(255, 255, 255));
        panelLlamadaEmocion.setGradiente(org.edisoncor.gui.panel.Panel.Gradiente.CENTRAL);
        panelLlamadaEmocion.setOrientacion(org.edisoncor.gui.panel.PanelLlamada.Orientacion.BOTTOM);
        panelLlamadaEmocion.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(radioEncanta);
        radioEncanta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meEncanta1.png"))); // NOI18N
        radioEncanta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meEncanta2.png"))); // NOI18N
        radioEncanta.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meEncanta3.png"))); // NOI18N
        radioEncanta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                reacciona(radioEncanta, radioSonroja, radioAsombra, radioDivierte, radioEntristece, radioEnoja, radioGusta, botonEmocion, panelLlamadaEmocion);
            }
        });
        panelLlamadaEmocion.add(radioEncanta, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 40, 30));

        buttonGroup1.add(radioSonroja);
        radioSonroja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meSonroja1.png"))); // NOI18N
        radioSonroja.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meSonroja2.png"))); // NOI18N
        radioSonroja.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meSonroja3.png"))); // NOI18N
        radioSonroja.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                reacciona(radioEncanta, radioSonroja, radioAsombra, radioDivierte, radioEntristece, radioEnoja, radioGusta, botonEmocion, panelLlamadaEmocion);
            }
        });
        panelLlamadaEmocion.add(radioSonroja, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 0, 30, 30));

        buttonGroup1.add(radioAsombra);
        radioAsombra.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meAsombra1.png"))); // NOI18N
        radioAsombra.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meAsombra2.png"))); // NOI18N
        radioAsombra.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meAsombra3.png"))); // NOI18N
        radioAsombra.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                reacciona(radioEncanta, radioSonroja, radioAsombra, radioDivierte, radioEntristece, radioEnoja, radioGusta, botonEmocion, panelLlamadaEmocion);
            }
        });
        panelLlamadaEmocion.add(radioAsombra, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, 40, 30));

        buttonGroup1.add(radioDivierte);
        radioDivierte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meDivierte1.png"))); // NOI18N
        radioDivierte.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meDivierte2.png"))); // NOI18N
        radioDivierte.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meDivierte3.png"))); // NOI18N
        radioDivierte.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                reacciona(radioEncanta, radioSonroja, radioAsombra, radioDivierte, radioEntristece, radioEnoja, radioGusta, botonEmocion, panelLlamadaEmocion);
            }
        });
        panelLlamadaEmocion.add(radioDivierte, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 0, 30, 30));

        buttonGroup1.add(radioEntristece);
        radioEntristece.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meEntristece1.png"))); // NOI18N
        radioEntristece.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meEntristece2.png"))); // NOI18N
        radioEntristece.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meEntristece3.png"))); // NOI18N
        radioEntristece.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                reacciona(radioEncanta, radioSonroja, radioAsombra, radioDivierte, radioEntristece, radioEnoja, radioGusta, botonEmocion, panelLlamadaEmocion);
            }
        });
        panelLlamadaEmocion.add(radioEntristece, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 30, 30));

        buttonGroup1.add(radioEnoja);
        radioEnoja.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meEnoja1.png"))); // NOI18N
        radioEnoja.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meEnoja2.png"))); // NOI18N
        radioEnoja.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meEnoja3.png"))); // NOI18N
        radioEnoja.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                reacciona(radioEncanta, radioSonroja, radioAsombra, radioDivierte, radioEntristece, radioEnoja, radioGusta, botonEmocion, panelLlamadaEmocion);
            }
        });
        panelLlamadaEmocion.add(radioEnoja, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 40, 30));

        buttonGroup1.add(radioGusta);
        radioGusta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meGusta1.png"))); // NOI18N
        radioGusta.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meGusta2.png"))); // NOI18N
        radioGusta.setSelectedIcon(new javax.swing.ImageIcon(getClass().getResource("/emociones/meGusta3.png"))); // NOI18N
        radioGusta.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                reacciona(radioEncanta, radioSonroja, radioAsombra, radioDivierte, radioEntristece, radioEnoja, radioGusta, botonEmocion, panelLlamadaEmocion);
            }
        });
        panelLlamadaEmocion.add(radioGusta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 30));

        panelEmocion.add(panelLlamadaEmocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 250, 40));

        botonEmocion.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        botonEmocion.setForeground(new java.awt.Color(153, 153, 153));
        botonEmocion.setText("Me gusta");
        botonEmocion.setContentAreaFilled(false);
        botonEmocion.addMouseMotionListener(new java.awt.event.MouseMotionAdapter()
        {
            public void mouseMoved(java.awt.event.MouseEvent evt)
            {
                panelLlamadaEmocion.setVisible(true);
                panelVerificarReaccion.setVisible(true);
                panelEmocion.setVisible(true);
            }
        });
        botonEmocion.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                botonEmocion.setForeground(new Color(153, 153, 153));
                botonEmocion.setText("Me gusta");
                botonEmocion.setIcon(null);
                panelLlamadaEmocion.setVisible(false);
            }
        });

        panelEmocion.add(botonEmocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 180, 30));
        panelEmocion.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 40, 310, 10));

        panelVerificarReaccion.add(panelEmocion, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, 260, 70));

        panelReaccion.add(panelVerificarReaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 310, 120));
//Panel para proyectar la imagen

        javax.swing.GroupLayout jPanelImagemLayout = new javax.swing.GroupLayout(jPanelImagem);
        jPanelImagem.setLayout(jPanelImagemLayout);
        jPanelImagemLayout.setHorizontalGroup(
                jPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 130, Short.MAX_VALUE)
        );
        jPanelImagemLayout.setVerticalGroup(
                jPanelImagemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 150, Short.MAX_VALUE)
        );

        panelReaccion.add(jPanelImagem, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 20, 130, -1));

        bntDescripcion.setBackground(new java.awt.Color(0, 51, 102));
        bntDescripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Up_24px.png"))); // NOI18N
        bntDescripcion.setText("Ver descripción");
        bntDescripcion.setColorHover(new java.awt.Color(0, 102, 204));
        bntDescripcion.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                /*
                Que se desea hacer si se oprime el botonVerDescripcion
                 */
                nombre_libro_s = etirquetaTituloLibro.getText();
                ProductInformationLibro ps = new ProductInformationLibro(nombre_libro_s);
                ps.setVisible(true);
            }
        });
        panelReaccion.add(bntDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 310, -1));
        panelLlamadaEmocion.setVisible(false);
        v.add(panelReaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 340, 360));
        return jPanelImagem;
    }

    public void reacciona(javax.swing.JRadioButton radioEncanta, javax.swing.JRadioButton radioSonroja, javax.swing.JRadioButton radioAsombra, javax.swing.JRadioButton radioDivierte, javax.swing.JRadioButton radioEntristece, javax.swing.JRadioButton radioEnoja, javax.swing.JRadioButton radioGusta, javax.swing.JToggleButton botonEmocion, org.edisoncor.gui.panel.PanelLlamada panelLlamadaEmocion)
    {
        if (radioEncanta.isSelected())
        {
            botonEmocion.setForeground(new Color(204, 0, 0));
            botonEmocion.setText("Me encanta");
            botonEmocion.setIcon(radioEncanta.getSelectedIcon());
            panelLlamadaEmocion.setVisible(false);
        } else if (radioSonroja.isSelected())
        {
            botonEmocion.setForeground(new Color(255, 204, 0));
            botonEmocion.setText("Me sonroja");
            botonEmocion.setIcon(radioSonroja.getSelectedIcon());
            panelLlamadaEmocion.setVisible(false);
        } else if (radioAsombra.isSelected())
        {
            botonEmocion.setForeground(new Color(255, 204, 0));
            botonEmocion.setText("Me asombra");
            botonEmocion.setIcon(radioAsombra.getSelectedIcon());
            panelLlamadaEmocion.setVisible(false);
        } else if (radioDivierte.isSelected())
        {
            botonEmocion.setForeground(new Color(255, 204, 0));
            botonEmocion.setText("Me divierte");
            botonEmocion.setIcon(radioDivierte.getSelectedIcon());
            panelLlamadaEmocion.setVisible(false);
        } else if (radioEntristece.isSelected())
        {
            botonEmocion.setForeground(new Color(255, 204, 0));
            botonEmocion.setText("Me entristece");
            botonEmocion.setIcon(radioEntristece.getSelectedIcon());
            panelLlamadaEmocion.setVisible(false);
        } else if (radioEnoja.isSelected())
        {
            botonEmocion.setForeground(new Color(204, 102, 0));
            botonEmocion.setText("Me enfada");
            botonEmocion.setIcon(radioEnoja.getSelectedIcon());

            panelLlamadaEmocion.setVisible(false);
        } else if (radioGusta.isSelected())
        {
            botonEmocion.setForeground(new Color(0, 102, 255));
            botonEmocion.setText("Me gusta");
            botonEmocion.setIcon(radioGusta.getSelectedIcon());
            panelLlamadaEmocion.setVisible(false);
        } else
        {
            botonEmocion.setForeground(new Color(153, 153, 153));
            botonEmocion.setText("Me gusta");
            botonEmocion.setIcon(null);
            panelLlamadaEmocion.setVisible(false);
        }
    }

    // int anchos[]={10,250,250,25};
    // for (int x = 0; x < jTablaUsuarios.getColumnCount(); x++)
    // {
    // jTablaUsuarios.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
    //}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JScrollPane jScrollPane4;
    private rojeru_san.RSButton rSButton2;
    private rojeru_san.RSButton rSButton3;
    private rojeru_san.RSMTextFull txtBuscarClave;
    // End of variables declaration//GEN-END:variables
}
