/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VntLibreria;

import java.applet.Applet;
import java.applet.AudioClip;
import java.awt.Desktop;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import java.awt.MouseInfo;
import java.awt.Point;
import java.net.URI;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import recursos.Mensaje;
import recursos.Validaciones;

/**
 *
 * @author HP
 */
public class VtnConsultarLibrerias extends javax.swing.JFrame
{

    /**
     * Creates new form VtnConsultarLibrerias
     */
    //VARIABLE ENTERA PARA CONOCER LA POSISION EN X DE LA VENTANA
    int X_V;
    //VARIABLE ENTERA PARA CONOCER LA POSISION EN Y DE LA VENTANA
    int Y_V;
    String pantallas_Usuario = "";
    String nombre_Final_de_Usuario = "";

    public VtnConsultarLibrerias(String pantallas_Usuario, String nombre_Final_de_Usuario)
    {
        initComponents();
         Image icono = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("imagenesG/buhoAzul.png"));
        setIconImage(icono);
        //   setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setResizable(false);
        this.setLocationRelativeTo(null);
     
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rSButton1 = new rojeru_san.RSButton();
        rSButton3 = new rojeru_san.RSButton();
        txtUsuario = new rojeru_san.RSMTextFull();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable1 = new rojerusan.RSTableMetro();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(870, 730));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("NOMBRE DE LIBRERÍA");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 180, -1, -1));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setText("Consultar Librerías");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 410, -1));

        rSButton1.setBackground(new java.awt.Color(0, 51, 102));
        rSButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Login_24px.png"))); // NOI18N
        rSButton1.setText("Regresar");
        rSButton1.setColorHover(new java.awt.Color(0, 153, 204));
        rSButton1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 160, 150, 40));

        rSButton3.setBackground(new java.awt.Color(0, 51, 102));
        rSButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/icons8_Search_31px.png"))); // NOI18N
        rSButton3.setText("Buscar");
        rSButton3.setColorHover(new java.awt.Color(0, 102, 204));
        rSButton3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                rSButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(rSButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 160, 150, 40));

        txtUsuario.setForeground(new java.awt.Color(0, 51, 102));
        txtUsuario.setBordeColorFocus(new java.awt.Color(0, 51, 102));
        txtUsuario.setBotonColor(new java.awt.Color(0, 51, 102));
        txtUsuario.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtUsuario.setOpaque(false);
        txtUsuario.addKeyListener(new java.awt.event.KeyAdapter()
        {
            public void keyReleased(java.awt.event.KeyEvent evt)
            {
                txtUsuarioKeyReleased(evt);
            }
        });
        jPanel1.add(txtUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, 240, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][]
            {

            },
            new String []
            {
                "ID de libreria", "Nombre", "Dirección", "Telefono", "Horario", "Correo"
            }
        )
        {
            boolean[] canEdit = new boolean []
            {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex)
            {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColorBackgoundHead(new java.awt.Color(0, 51, 102));
        jTable1.setColorBordeFilas(new java.awt.Color(204, 204, 204));
        jTable1.setColorBordeHead(new java.awt.Color(204, 204, 204));
        jTable1.setColorFilasForeground1(new java.awt.Color(0, 0, 51));
        jTable1.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        jTable1.setFuenteHead(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jScrollPane4.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0)
        {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel1.add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 1200, 310));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1260, 580));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void rSButton1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton1ActionPerformed
    {//GEN-HEADEREND:event_rSButton1ActionPerformed
        CtrComponentes.botonSalirSI(this, nombre_Final_de_Usuario, pantallas_Usuario);
    }//GEN-LAST:event_rSButton1ActionPerformed

    private void rSButton3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_rSButton3ActionPerformed
    {//GEN-HEADEREND:event_rSButton3ActionPerformed

        modelo = new DefaultTableModel();
        modelo.addColumn("ID LIBRERIA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("HORARIO");
        modelo.addColumn("CORREO");

        jTable1.setModel(modelo);
        // int anchos[]={10,250,250,25};
        // for (int x = 0; x < jTablaUsuarios.getColumnCount(); x++)
        // {
        // jTablaUsuarios.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
        //}

        String sql = "";
        if (txtUsuario.getText().equals(""))
        {
            sql = "SELECT * FROM t_libreria";
        } else
        {

            sql = "SELECT * FROM t_libreria WHERE nombre_libreria like '%" + txtUsuario.getText() + "%'";

        }

        String datos[] = new String[6];
        Statement st;
        Conexion.con = Conexion.getConexion();
        try
        {
            st = Conexion.con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
                datos[0] = rs.getString("id_libreria");
                datos[1] = rs.getString("nombre_libreria");
                datos[2] = rs.getString("dir_libreria");
                datos[3] = rs.getString("tel_libreria");
                datos[4] = rs.getString("hora_abrir") + "-" + rs.getString("hora_cerrar");
                datos[5] = rs.getString("correo_libreria");
                modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch (Exception e)
        {
            Mensaje.errorException(this, "Ha ocurrido un error \n" + e.toString());
        }

    }//GEN-LAST:event_rSButton3ActionPerformed

    private void txtUsuarioKeyReleased(java.awt.event.KeyEvent evt)//GEN-FIRST:event_txtUsuarioKeyReleased
    {//GEN-HEADEREND:event_txtUsuarioKeyReleased

        modelo = new DefaultTableModel();
        modelo.addColumn("ID LIBRERIA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("HORARIO");
        modelo.addColumn("CORREO");

        jTable1.setModel(modelo);
        // int anchos[]={10,250,250,25};
        // for (int x = 0; x < jTablaUsuarios.getColumnCount(); x++)
        // {
        // jTablaUsuarios.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
        //}

        String sql = "";
        if (txtUsuario.getText().equals(""))
        {
            sql = "SELECT * FROM t_libreria";
        } else
        {

            sql = "SELECT * FROM t_libreria WHERE nombre_libreria like '%" + txtUsuario.getText() + "%'";

        }

        String datos[] = new String[6];
        Statement st;
        Conexion.con = Conexion.getConexion();
        try
        {
            st = Conexion.con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
                datos[0] = rs.getString("id_libreria");
                datos[1] = rs.getString("nombre_libreria");
                datos[2] = rs.getString("dir_libreria");
                datos[3] = rs.getString("tel_libreria");
                datos[4] = rs.getString("hora_abrir") + "-" + rs.getString("hora_cerrar");
                datos[5] = rs.getString("correo_libreria");
                modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch (Exception e)
        {
            Mensaje.errorException(this, "Ha ocurrido un error \n" + e.toString());
        }
    }//GEN-LAST:event_txtUsuarioKeyReleased
    DefaultTableModel modelo;

    public void mostrar(String clave)
    {

        modelo = new DefaultTableModel();
        modelo.addColumn("ID LIBRERIA");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("TELEFONO");
        modelo.addColumn("HORARIO");
        modelo.addColumn("CORREO");

        jTable1.setModel(modelo);
        // int anchos[]={10,250,250,25};
        // for (int x = 0; x < jTablaUsuarios.getColumnCount(); x++)
        // {
        // jTablaUsuarios.getColumnModel().getColumn(x).setPreferredWidth(anchos[x]);
        //}

        String sql = "";
        if (clave.equals(""))
        {
            sql = "SELECT * FROM t_libreria";
        } else
        {

            sql = "SELECT * FROM t_libreria WHERE nombre_libreria like '%" + clave + "%'";

        }

        String datos[] = new String[6];
        Statement st;
        Conexion.con = Conexion.getConexion();
        try
        {
            st = Conexion.con.createStatement();
            ResultSet rs = st.executeQuery(sql);
            while (rs.next())
            {
                datos[0] = rs.getString("id_libreria");
                datos[1] = rs.getString("nombre_libreria");
                datos[2] = rs.getString("dir_libreria");
                datos[3] = rs.getString("tel_libreria");
                datos[4] = rs.getString("hora_abrir") + "-" + rs.getString("hora_cerrar");
                datos[5] = rs.getString("correo_libreria");
                modelo.addRow(datos);
            }
            jTable1.setModel(modelo);
        } catch (Exception e)
        {
            Mensaje.errorException(this, "Ha ocurrido un error \n" + e.toString());
        }

    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane4;
    private rojerusan.RSTableMetro jTable1;
    private rojeru_san.RSButton rSButton1;
    private rojeru_san.RSButton rSButton3;
    private rojeru_san.RSMTextFull txtUsuario;
    // End of variables declaration//GEN-END:variables
}
