/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package VntLibreria;

import com.mysql.jdbc.Connection;
import java.awt.Image;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.JFrame;
import static javax.swing.WindowConstants.DISPOSE_ON_CLOSE;

import org.edisoncor.gui.util.Avatar;
import recursos.Mensaje;

/**
 *
 * @author HP
 */
public class VtnMenuOpcion extends javax.swing.JInternalFrame
{

    /**
     * Creates new form VtnMenuOpcion
     */
    JFrame jf;
    String pantallas_Usuario = "";
    String nombre_Final_de_Usuario = "";

    public VtnMenuOpcion(JFrame jf, String pantallas_Usuario, String nombre_Final_de_Usuario)
    {
        this.nombre_Final_de_Usuario = nombre_Final_de_Usuario;
        this.pantallas_Usuario = pantallas_Usuario;
        this.jf = jf;
        initComponents();

        llenarMenu();

    }
    
    public VtnMenuOpcion()
    {
        initComponents();

        llenarMenu();

    }
    List<Avatar> avatars = new ArrayList<>();

    public void llenarMenu()
    {

        avatars.add(new Avatar("Alejandro Sánchez", loadImage("/autores/a1.jpg")));
        avatars.add(new Avatar("Ana Paula Ordorica", loadImage("/autores/a2.jpg")));
        avatars.add(new Avatar("Andrés Oppenheimer", loadImage("/autores/a3.jpg")));
        avatars.add(new Avatar("Antoni Bolinches", loadImage("/autores/a4.jpg")));

        avatars.add(new Avatar("Carlos Mota", loadImage("/autores/a6.jpg")));

        avatars.add(new Avatar("Héctor Manjarrez", loadImage("/autores/a9.jpg")));
        avatars.add(new Avatar("Jorge Carrión", loadImage("/autores/a10.jpg")));

        avatars.add(new Avatar("José Luis Treba Lara", loadImage("/autores/a12.jpg")));

        avatars.add(new Avatar("Marcela Turati", loadImage("/autores/a18.jpg")));
        avatars.add(new Avatar("Martha Alicia Chavez", loadImage("/autores/a19.jpg")));

        avatars.add(new Avatar("Paulo Coelho", loadImage("/autores/a21.jpg")));
       
        avatars.add(new Avatar("Rose Mary Espinosa", loadImage("/autores/a23.jpg")));
        panelAvatarChooser1.setAvatars(avatars);
        panelAvatarChooser1.setColorPrimario(VtnPrincipal.colorPP);
        panelAvatarChooser1.setColorSecundario(VtnPrincipal.colorPP);
        jPanel1.setBackground(VtnPrincipal.colorPP);
        
    }

    public static Image loadImage(String file)
    {
        try
        {
            return ImageIO.read(VtnProgrmador.class.getResource(file));
        } catch (Exception e)
        {
            Mensaje.errorException(null, "Ha ocurrido un error \n" + e.toString());
            return null;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        panelAvatarChooser1 = new org.edisoncor.gui.panel.PanelAvatarChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();

        jMenuItem9.setText("Ver libro");
        jPopupMenu1.add(jMenuItem9);

        jMenuItem10.setText("Eliminar de esta lista");
        jPopupMenu1.add(jMenuItem10);

        jMenuItem5.setText("jMenuItem5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Ventana programador");
        setToolTipText("");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panelAvatarChooser1.setAmount(7);
        panelAvatarChooser1.setColorPrimario(new java.awt.Color(0, 0, 102));
        panelAvatarChooser1.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.add(panelAvatarChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 430));

        jMenuBar1.setPreferredSize(new java.awt.Dimension(94, 40));

        jMenu1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/1055107 - bookshelf.png"))); // NOI18N
        jMenu1.setText("Libros");

        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118925 - all edit select.png"))); // NOI18N
        jMenuItem1.setText("Altas");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuItem2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118920 - delete edit.png"))); // NOI18N
        jMenuItem2.setText("Bajas");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem2);

        jMenuItem3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118921 - edit find replace.png"))); // NOI18N
        jMenuItem3.setText("Modificaciones");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem3);

        jMenu5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118922 - edit find.png"))); // NOI18N
        jMenu5.setText("Consultas");

        jMenuItem7.setText("Preterminda");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem7);

        jMenuItem8.setText("Personalizada");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem8);

        jMenu1.add(jMenu5);

        jMenuBar1.add(jMenu1);

        jMenu2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/1055000 - profle.png"))); // NOI18N
        jMenu2.setText("Usuarios");

        jMenuItem11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118925 - all edit select.png"))); // NOI18N
        jMenuItem11.setText("Altas");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem11);

        jMenuItem12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118920 - delete edit.png"))); // NOI18N
        jMenuItem12.setText("Bajas");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem12);

        jMenuItem13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118921 - edit find replace.png"))); // NOI18N
        jMenuItem13.setText("Modificaciones");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem13);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118922 - edit find.png"))); // NOI18N
        jMenuItem14.setText("Consultar");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem14);

        jMenuItem4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/118760 - fill format justify.png"))); // NOI18N
        jMenuItem4.setText("Generar reporte");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuBar1.add(jMenu2);

        jMenu3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/1054957 - tools.png"))); // NOI18N
        jMenu3.setText("Configuración");

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("Modo oscuro");
        jCheckBoxMenuItem1.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jCheckBoxMenuItem1ActionPerformed(evt);
            }
        });
        jMenu3.add(jCheckBoxMenuItem1);

        jMenuItem6.setText("Color de Tema");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem6);

        jMenuBar1.add(jMenu3);

        jMenu4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenesG/1054988 - running.png"))); // NOI18N
        jMenu4.setText("Cerrar Sesión");
        jMenu4.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenu4ActionPerformed(evt);
            }
        });

        jMenuItem15.setText("Cerrar Sesión");
        jMenuItem15.addActionListener(new java.awt.event.ActionListener()
        {
            public void actionPerformed(java.awt.event.ActionEvent evt)
            {
                jMenuItem15ActionPerformed(evt);
            }
        });
        jMenu4.add(jMenuItem15);

        jMenuBar1.add(jMenu4);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 944, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 286, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 435, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenu4ActionPerformed
    {//GEN-HEADEREND:event_jMenu4ActionPerformed
        new VtnPrincipal().setVisible(true);
        jf.dispose();
    }//GEN-LAST:event_jMenu4ActionPerformed

    private void jCheckBoxMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jCheckBoxMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jCheckBoxMenuItem1ActionPerformed
        if (jCheckBoxMenuItem1.isSelected())
        {
            VtnPrincipal.colorPP = VtnPrincipal.colorPO;
        } else
        {
            VtnPrincipal.colorPP = VtnPrincipal.colorPC;
        }

    }//GEN-LAST:event_jCheckBoxMenuItem1ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem1ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem1ActionPerformed
        new VtnRegistroLibros(pantallas_Usuario, nombre_Final_de_Usuario).setVisible(true);
        jf.dispose();
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem2ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem2ActionPerformed
        new VtnBajasLibros(pantallas_Usuario, nombre_Final_de_Usuario).setVisible(true);
        jf.dispose();
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem3ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem3ActionPerformed
        new VtnModificarLibros(pantallas_Usuario, nombre_Final_de_Usuario).setVisible(true);
        jf.dispose();
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem11ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem11ActionPerformed
        new VtnRegistroUsuario(pantallas_Usuario, nombre_Final_de_Usuario).setVisible(true);
        jf.dispose();
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem12ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem12ActionPerformed
        new VtnBajasAdministradores(pantallas_Usuario, nombre_Final_de_Usuario).setVisible(true);
        jf.dispose();
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem13ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem13ActionPerformed
        new VtnModificarUsuarios(pantallas_Usuario, nombre_Final_de_Usuario).setVisible(true);
        jf.dispose();
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem7ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem7ActionPerformed
        new VtnConsultarLibros(pantallas_Usuario, nombre_Final_de_Usuario).setVisible(true);
        jf.dispose();
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem15ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem15ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem15ActionPerformed
        NotificacionSesionCerrada n = new NotificacionSesionCerrada();
        n.setVisible(true);
        jf.dispose();
    }//GEN-LAST:event_jMenuItem15ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem8ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem8ActionPerformed
        new VtnConsultaPersonalizadaLibros(pantallas_Usuario, nombre_Final_de_Usuario).setVisible(true);
        jf.dispose();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem14ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem14ActionPerformed
        new VtnConsultarAdministradores(pantallas_Usuario, nombre_Final_de_Usuario).setVisible(true);
        jf.dispose();
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem6ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem6ActionPerformed

    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt)//GEN-FIRST:event_jMenuItem4ActionPerformed
    {//GEN-HEADEREND:event_jMenuItem4ActionPerformed
        try
        {
            Conexion con = new Conexion();
            Connection conn = con.getConexion();

        //    JasperReport reporte = null;
            //direccion del archivo
            String path = "src\\Reportes\\DICCIONARIO_DE_DATOS_LIBRERIA_VIRTUAL.xlsx";

            Map parametro = new HashMap();
            parametro.put("id", 2);//nombre

          //  reporte = (JasperReport) JRLoader.loadObjectFromFile(path);
            //                                                         null si no queremos enviar parametros 
            //JasperPrint jprint = JasperFillManager.fillReport(reporte, null, conn);

            //JasperViewer view = new JasperViewer(jprint, false);

            //view.setDefaultCloseOperation(DISPOSE_ON_CLOSE);

            //view.setVisible(true);

        } catch (Exception ex)
        {
            Logger.getLogger(Inicio.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jMenuItem4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private org.edisoncor.gui.panel.PanelAvatarChooser panelAvatarChooser1;
    // End of variables declaration//GEN-END:variables
}
